server:
  port: ${CATELOG_SERVER_PORT:8300}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb.default/${MONGO_DATABASE}
      authentication-database: admin

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.usl.microservices: DEBUG

